

<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
          <li><a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">&laquo;</a></li>
        <?php else: ?>
          <li><a class="disabled">&laquo;</a><li>
        <?php endif; ?>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != $this->current): ?>
            <li><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?php echo $page; ?></a></li>
          <?php else: ?>
            <li><a class="disabled"><?php echo $page; ?></a></li>
          <?php endif; ?>
        <?php endforeach; ?>
        
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
          <li><a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">&raquo;</a></li>
        <?php else: ?>
          <li><a class="disabled">&raquo;</a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>