<div class="searchbox">
    <div class="searchfrm">

        <?php echo $this->form()->openTag($form); ?>


        <div class="col-md-3">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('city')); ?>
                <div class="input-group input-group-md">
                    <span class="input-group-addon"><i class="fa fa-location-arrow"></i></span>
                    <?php echo $this->formElement($form->get('city')); ?>
                </div>
                <?php echo $this->formElementErrors($form->get('city')); ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('country_id')); ?>
                <div class="input-group input-group-md">
                    <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                    <?php echo $this->formElement($form->get('country_id')); ?>
                </div>
                <?php echo $this->formElementErrors($form->get('country_id')); ?>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('category_id')); ?>
                <div class="input-group input-group-md">
                    <span class="input-group-addon"><i class="fa fa-tags"></i></span>
                    <?php echo $this->formElement($form->get('category_id')); ?>
                </div>
                <?php echo $this->formElementErrors($form->get('category_id')); ?>
            </div>
        </div>


        <div class="col-md-3">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('content')); ?>
                <div class="input-group input-group-md">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <?php echo $this->formElement($form->get('content')); ?>
                </div>
                <?php echo $this->formElementErrors($form->get('content')); ?>
            </div>
        </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
    <div class="searchbtn" title="<?php echo $this->translate('Open or Close the search box') ?>"><a href="#"><i class="fa fa-plus-square"></i> <?php echo $this->translate('Open/Close') ?></a></div>

</div>