<?php $this->headTitle()->prepend($this->translate('Event - List of all pages')); ?>

<div class="row header">
    <div class="col-lg-10">
        <div class="page-header">
            <h1><i class="fa fa-list"></i> <?php echo $this->translate('Event Pages') ?> <small><?php echo $this->translate('Create new site content') ?></small></h1>
            <?php echo $this->translate('This is the list of all pages of this site.') ?>
        </div>
    </div>
    <?php if ($this->error): ?>
        <div class="col-lg-12">
            <div class="alert alert-warning">
                <?php echo $this->translate('There were one or more issues with your submission. Please correct them as indicated below.') ?>
            </div>
        </div>
    <?php endif ?>
</div>

<?php echo $this->grid ?>

<hr />
<a href="/admin/events/add">&raquo <?php echo $this->translate('Add event') ?></a>