<?php $this->headTitle()->prepend($this->translate('Edit event')); ?>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/ckeditor.js'); ?>

<?php 
    $event = $this->event;
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', '/myevents/save');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);

?>

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <?php if(!empty($event)): ?>
                  <?php if($event->getVisible()): ?>
                      <h2><a href="/events/<?php echo $event->getSlug() ?>.html"><?php echo $event->getTitle() ?></a></h2>
                  <?php else: ?>
                      <h2><?php echo $event->getTitle() ?></h2>
                  <?php endif; ?>
                  <small><?php echo $this->translate('Improve the description of your event to well promote the event!')?></small>
                  <?php echo $this->tags($event->getTags())?>
              <?php else: ?>
                <h2><?php echo $this->translate('New Event') ?> <small><?php echo $this->translate('Create a new event now!') ?></small></h2>
            <?php endif; ?>
        </div>
        <div class="col-lg-4"><br/>
        	<div class="text-right">
    		    <a href="/myevents/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
    		    <a href="/myevents/list" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
                <?php if($event): ?>
                    <a href="/myevents/clone/<?php echo $event->getSku() ?>" onclick="return confirm('<?php echo $this->translate('Are you sure?') ?>')" class="btn btn-warning"><i class="fa fa-recycle"></i> <?php echo $this->translate('Clone')?></a>
                    <a href="/myevents/delete/<?php echo $event->getId() ?>" onclick="return confirm('<?php echo $this->translate('Are you sure?') ?>')" class="btn btn-danger"><i class="fa fa-recycle"></i> <?php echo $this->translate('Delete')?></a>
                <?php endif; ?>
    		</div>
    	</div>
    </div>
    <hr/>
        <?php if ($this->error): ?>
            <div class="row">
    	        <div class="col-lg-12">
    	            <div class="alert alert-warning">
                        <?php echo $this->translate('There were one or more issues with your submission. Please correct them as indicated below.') ?>
    	            </div>
    	        </div>
            </div>
        <?php endif ?>
    
    <div class="row">
    	<div class="col-lg-12">
            <div class="pull-right"><?php echo $this->translate('All star (*) marked fields are mandatory!') ?></div>
            <br/>
    		<div class="tabbable" id="tabs">
    			<ul class="nav nav-tabs">
    				<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
    				<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Venue');?></a></li>
    				<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('File / Photo');?></a></li>
    				<li><a data-toggle="tab" href="#tab5"><?php echo $this->translate('Options');?></a></li>
    				<li><a data-toggle="tab" href="#tab6"><?php echo $this->translate('Help');?></a></li>
    			</ul>
    			<div class="tab-content">
    			    <div class="tab-pane active" id="tab1">
    			    
    			        <div class="row">
    			            <?php if($event): ?>
        			            <div class="<?php echo ($event->getFile()) ? "col-md-4" : "hidden" ?>">
            			             <?php if($event->getFile()): ?>
            			                 <?php if (@!is_array(getimagesize($event->getFile()))): ?>
                                            <img width="300" class="img-responsive img-rounded img-within-content" src="<?php echo $event->getFile() ?>">
                                         <?php else: ?>
                                             <a href="<?php echo $event->getFile() ?>"><?php echo $this->translate('Download') ?></a>
                                         <?php endif; ?>
                                        <a onclick="return confirm('<?php echo $this->translate('Are you sure?') ?>')" href="/myevents/delfile/<?php echo $event->getId() ?>" class="btn btn-danger"><?php echo $this->translate('Delete')?></a>
                                     <?php endif; ?>
        			            </div>
    			            <?php endif;?>
    			            <?php if($event): ?>
        			            <div class="<?php echo ($event->getFile()) ? "col-md-8" : "col-md-12" ?>">
        			        <?php else:?>
        			            <div class="col-md-12">
        			        <?php endif;?>
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('title')); ?> *
                                    <?php echo $this->formElement($form->get('title')); ?>
                                    <?php echo $this->formElementErrors($form->get('title')); ?>
                                </div>
                                
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('category_id')); ?>
                                    <?php echo $this->formElement($form->get('category_id')); ?>
                                    <?php echo $this->formElementErrors($form->get('category_id')); ?>
                                </div>

                                
    			            </div>
                            
    		            </div>
    	                <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('start')); ?> *
                                    <div class="input-group input-group-md">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        <?php echo $this->formElement($form->get('start')); ?>
                                    </div>
                                    <?php echo $this->formElementErrors($form->get('start')); ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('end')); ?> *
                                    <div class="input-group input-group-md">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        <?php echo $this->formElement($form->get('end')); ?>
                                    </div>
                                    <?php echo $this->formElementErrors($form->get('end')); ?>
                                </div>
                            </div>    
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('content')); ?> *
                            <?php echo $this->formElement($form->get('content')); ?>
                            <?php echo $this->formElementErrors($form->get('content')); ?>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab3">

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('place')); ?>
                                    <?php echo $this->formElement($form->get('place')); ?>
                                    <?php echo $this->formElementErrors($form->get('place')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('country_id')); ?>
                                    <?php echo $this->formElement($form->get('country_id')); ?>
                                    <?php echo $this->formElementErrors($form->get('country_id')); ?>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('city')); ?>
                                    <div class="input-group input-group-md">
                                        <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                                        <?php echo $this->formElement($form->get('city')); ?>
                                    </div>
                                    <?php echo $this->formElementErrors($form->get('city')); ?>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('address')); ?>
                            <div class="input-group input-group-md">
                                <span class="input-group-addon"><i class="fa fa-location-arrow"></i></span>
                                <?php echo $this->formElement($form->get('address')); ?>
                            </div>
                            <?php echo $this->formElementErrors($form->get('address')); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('contact')); ?>
                            <div class="input-group input-group-md">
                                <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                                <?php echo $this->formElement($form->get('contact')); ?>
                            </div>
                            <?php echo $this->formElementErrors($form->get('contact')); ?>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab4">
                    	<div class="form-group">
                            <?php echo $this->formLabel($form->get('file')); ?>
                            <?php echo $this->formElement($form->get('file')); ?>
                            <?php echo $this->formElementErrors($form->get('file')); ?>
                        </div>
                    </div>
    		   	    <div class="tab-pane" id="tab5">

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('parent_id')); ?>
                            <div class="input-group input-group-md">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                <?php echo $this->formElement($form->get('parent_id')); ?>
                            </div>
                            <?php echo $this->formElementErrors($form->get('parent_id')); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('tags')); ?>
                            <?php echo $this->formElement($form->get('tags')); ?>
                            <?php echo $this->formElementErrors($form->get('tags')); ?>
                        </div>


                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('url')); ?>
                            <div class="input-group input-group-md">
                                <span class="input-group-addon"><i class="fa fa-link"></i></span>
                                <?php echo $this->formElement($form->get('url')); ?>
                            </div>
                            <?php echo $this->formElementErrors($form->get('url')); ?>
                        </div>
                    </div>
    		   	    <div class="tab-pane" id="tab6">
                        <?php echo $this->partial('events/partial/help.phtml'); ?>
                    </div>
    		   	</div>
    		</div>
    	</div>
    </div>
        <div class="text-right">
            <?php echo $this->formElement($form->get('submit')); ?>
        </div>
    </div>
</div>
<?php echo $this->formElement($form->get('id')); ?>
<?php echo $this->formElement($form->get('sku')); ?>

<?php echo $this->form()->closeTag() ?>
