
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h2><i class="fa fa-calendar"></i> <?php echo $this->translate('Confirmed Events')?> <small><?php echo $this->translate('Manage your events')?></small></h2>
            <p><?php echo $this->translate('Here you can edit or delete your events.')?>
        </div>
        
        <div class="col-lg-5 text-right">
            <a class="btn btn-warning" href="/myevents/social"><i class="fa fa-calendar"></i> <?php echo $this->translate('Pending')?></a>
            <a class="btn btn-danger" onclick="return confirm('<?php echo $this->translate('All events will be deleted but if you have a google calendar or facebook events service connected to this website, the events will be synced again! Are you sure to delete the confirmed events?') ?>')" href="/myevents/cleanup"><i class="fa fa-trash"></i> <?php echo $this->translate('Delete All')?></a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <?php echo $this->grid ?>
        </div>
    </div>
</div>