<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h2><i class="fa fa-calendar"></i> <?php echo $this->translate('Pending Events')?> <br/><small><?php echo $this->translate('Managing your pending events')?></small></h2>
            <p><?php printf($this->translate('Here you will see all the events that are fetched from the Google Calendar and/or Facebook page events. If they will be confirmed you will see them in the confirmed events page. %s'), '<a href="/myevents"><i class="fa fa fa-external-link-square"></i> Events</a>')?><br/>
            <?php printf($this->translate('In order to fetch all the Google Calendar events click here %s. If you need to fetch all the facebook events click here %s'), '<a href="/google"><i class="fa fa-google"></i> Google</a>', '<a href="/facebook"><i class="fa fa-facebook"></i> Facebook</a>')?>
            <?php echo $this->translate('Here you can see events from Facebook and Google. The events will be synced every 10 minutes.')?>
            </p>
         </div>
         <div class="col-lg-5 text-right"><br/><br/>
            <a class="btn btn-success" href="/myevents"><i class="fa fa-calendar"></i> <?php echo $this->translate('Confirmed Events')?></a>
            <a class="btn btn-danger" onclick="return confirm('<?php echo $this->translate('The pending events will be deleted but if your facebook events service is connected the events will be synced again! The google calendar events will be not synced automatically until at least one of your event will be updated in your calendar! Are you sure to delete all the pending events?') ?>')" href="/myevents/social/delete"><i class="fa fa-trash"></i> <?php echo $this->translate('Delete All')?></a>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-12">
            <?php echo $this->grid ?>
        </div>
    </div>
</div>